/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.helloworldapp;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Harsh Chandel
 */
public class candidateHome extends javax.swing.JFrame {

    /**
     * Creates new form candidateHome
     * @param id
     * @param v
     */
    boolean c;
    public candidateHome(String id,boolean v) {
        c=v;
        this.id=id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        organizeMeeting = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        deleteAnEvent = new javax.swing.JButton();
        welcomeTitle = new javax.swing.JLabel();
        viewSchedule = new javax.swing.JButton();
        BookSlot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Candidate Home");

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 0)));

        organizeMeeting.setBackground(new java.awt.Color(0, 51, 255));
        organizeMeeting.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        organizeMeeting.setText("Organize A Meeting");
        organizeMeeting.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        organizeMeeting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizeMeetingActionPerformed(evt);
            }
        });

        logOut.setBackground(new java.awt.Color(255, 0, 0));
        logOut.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        logOut.setText("Log Out");
        logOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(255, 255, 255), java.awt.Color.white, java.awt.Color.white));
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        deleteAnEvent.setBackground(new java.awt.Color(0, 0, 255));
        deleteAnEvent.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        deleteAnEvent.setText("Delete an  event");
        deleteAnEvent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        deleteAnEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAnEventActionPerformed(evt);
            }
        });

        welcomeTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        welcomeTitle.setText("     Welcome");

        viewSchedule.setBackground(new java.awt.Color(51, 51, 255));
        viewSchedule.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        viewSchedule.setText("View Schedule");
        viewSchedule.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        viewSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewScheduleActionPerformed(evt);
            }
        });

        BookSlot.setBackground(new java.awt.Color(0, 51, 255));
        BookSlot.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        BookSlot.setText("Book A Slot");
        BookSlot.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        BookSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookSlotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(welcomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(logOut)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(organizeMeeting, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteAnEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(viewSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BookSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logOut))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizeMeeting, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteAnEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewScheduleActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new viewSchedule(id,c).setVisible(true);        
    }//GEN-LAST:event_viewScheduleActionPerformed

    private void BookSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookSlotActionPerformed
        // TODO add your handling code here:
        if(!c){
        new accessBlocked().setVisible(true);
        }
        else {
        this.setVisible(false);
        new bookSlot(id,c).setVisible(true);
        }
    }//GEN-LAST:event_BookSlotActionPerformed

    private void organizeMeetingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizeMeetingActionPerformed
            // TODO add your handling code here:
            if(!c){
        new accessBlocked().setVisible(true);
        }
        else {
        this.setVisible(false);
        new organizeMeeting(id,c).setVisible(true);
            }
    }//GEN-LAST:event_organizeMeetingActionPerformed

    private void deleteAnEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAnEventActionPerformed
        // TODO add your handling code here:
            if(!c){
        new accessBlocked().setVisible(true);
        }
        else {
            
        this.setVisible(false);
        new deleteEvent(id,c).setVisible(true);
            }
    }//GEN-LAST:event_deleteAnEventActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new login2().setVisible(true);
    }//GEN-LAST:event_logOutActionPerformed

    /**
     * @param args the command line arguments
     */
    private String id;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookSlot;
    private javax.swing.JButton deleteAnEvent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logOut;
    private javax.swing.JButton organizeMeeting;
    private javax.swing.JButton viewSchedule;
    private javax.swing.JLabel welcomeTitle;
    // End of variables declaration//GEN-END:variables
}
