/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.helloworldapp;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Harsh Chandel
 */
public class viewStatistics extends javax.swing.JFrame {

    /**
     * Creates new form viewStatistics
     * @param x
     */
    String id;
    public viewStatistics(String x) {
        id=x;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        labelProject = new javax.swing.JLabel();
        projectIdText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        employeeIdText = new javax.swing.JTextField();
        labelHeading = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Statistics");

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        submitButton.setBackground(new java.awt.Color(0, 0, 255));
        submitButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        labelProject.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        labelProject.setText("Project Id:");

        projectIdText.setBackground(new java.awt.Color(153, 153, 255));
        projectIdText.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        projectIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectIdTextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setText("Employee Id:");

        employeeIdText.setBackground(new java.awt.Color(153, 153, 255));
        employeeIdText.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        labelHeading.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        labelHeading.setText("View Statistics");

        backButton.setBackground(new java.awt.Color(255, 0, 51));
        backButton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        backButton.setText("<");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(labelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(employeeIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelProject)
                                    .addGap(34, 34, 34)
                                    .addComponent(projectIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(submitButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProject)
                    .addComponent(projectIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(employeeIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projectIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectIdTextActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        String u=projectIdText.getText();
        String v=employeeIdText.getText();
        String textArea="Statistics for ";
        if(u.length()==0&&v.length()==0){
              new displayStats("Enter some data to view statistics").setVisible(true);
        }
        else if(u.length()==0) {
             textArea+= "employee "+v+" is shown below\n";
             
                try {
            Connection connection = DriverManager.getConnection("jdbc:mariadb://localhost:3306/TMS", "root", "illuminaty");
             PreparedStatement Stmt=connection.prepareStatement("select * from meetings where emp_id=? order by date,timeslot");
             Stmt.setString(1,v);
             ResultSet rs=Stmt.executeQuery();
             int counter=1;
             while(rs.next()){
                 int t=rs.getInt("timeslot");
                 String venue= rs.getString("venue");
                 String p=rs.getString("project_id");
                          if(p.length()!=0)     textArea+=(String.format("%d. ",counter)+"Meeting for "+p+" on timeslot:"+String.format("%d",t)+" at "+venue+" on date:"+rs.getString("date")+" for employee:"+rs.getString("emp_id")+"\n");
                          else textArea+=(String.format("%d. ",counter)+"Employee "+rs.getString("emp_id")+" Unavailable on timeslot:"+String.format("%d",t)+" on date:"+rs.getString("date")+"\n");
                counter++; 
             }
             textArea+="Found "+String.format("%d ",counter-1)+"enteries";
             Stmt.close();
             connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(login2.class.getName()).log(Level.SEVERE, null, ex);
        }
             new displayStats(textArea).setVisible(true);
        }
        else if(v.length()==0) {
                 textArea+= "prject "+u+" is shown below\n";
             
                try {
            Connection connection = DriverManager.getConnection("jdbc:mariadb://localhost:3306/TMS", "root", "illuminaty");
             PreparedStatement Stmt=connection.prepareStatement("select * from meetings where project_id=? order by date,timeslot");
             Stmt.setString(1,u);
             ResultSet rs=Stmt.executeQuery();
             int counter=1;
             while(rs.next()){
                 int t=rs.getInt("timeslot");
                 String venue= rs.getString("venue");
                 String p=rs.getString("project_id");
               if(p.length()!=0)     textArea+=(String.format("%d. ",counter)+"Meeting for "+p+" on timeslot:"+String.format("%d",t)+" at "+venue+" on date:"+rs.getString("date")+" for employee:"+rs.getString("emp_id")+"\n");
                          else textArea+=(String.format("%d. ",counter)+"Employee "+rs.getString("emp_id")+" Unavailable on timeslot:"+String.format("%d",t)+" on date:"+rs.getString("date")+"\n");
                 counter++; 
             }
             textArea+="Found "+String.format("%d ",counter-1)+"enteries";
             Stmt.close();
             connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(login2.class.getName()).log(Level.SEVERE, null, ex);
        }
             new displayStats(textArea).setVisible(true);
        
        }
        else {
                 textArea+= "employee "+v+" and project "+u+" is shown below\n";
             
                try {
            Connection connection = DriverManager.getConnection("jdbc:mariadb://localhost:3306/TMS", "root", "illuminaty");
             PreparedStatement Stmt=connection.prepareStatement("select * from meetings where emp_id=? and project_id=? order by date,timeslot");
             Stmt.setString(1,v);
             Stmt.setString(2,u);
             ResultSet rs=Stmt.executeQuery();
             int counter=1;
             while(rs.next()){
                 int t=rs.getInt("timeslot");
                 String venue= rs.getString("venue");
                 String p=rs.getString("project_id");
               if(p.length()!=0)     textArea+=(String.format("%d. ",counter)+"Meeting for "+p+" on timeslot:"+String.format("%d",t)+" at "+venue+" on date:"+rs.getString("date")+" for employee:"+rs.getString("emp_id")+"\n");
                          else textArea+=(String.format("%d. ",counter)+"Employee "+rs.getString("emp_id")+" Unavailable on timeslot:"+String.format("%d",t)+" on date:"+rs.getString("date")+"\n");
                 counter++; 
             }
             textArea+="Found "+String.format("%d ",counter-1)+"enteries";
             Stmt.close();
             connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(login2.class.getName()).log(Level.SEVERE, null, ex);
        }
             new displayStats(textArea).setVisible(true);
        
        } 
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AdminHome(id).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField employeeIdText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelHeading;
    private javax.swing.JLabel labelProject;
    private javax.swing.JTextField projectIdText;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
